<head>
    <meta charset="utf-8" />
    <meta name="description" content="This is the About Page" />
    <meta name="keywords" content="" />
    <meta name="author" content="Thomas" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Curly Brace Technologies | <?php echo $title; ?> </title>
    <link rel="icon" type="image/x-icon" href="./images/logo.png">
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=Fira+Code:wght@300;400;500;600;700"
      rel="stylesheet"
    />
    <link href="./styles/style.css" rel="stylesheet" type="text/css" />
  </head>