    <header>
      <nav>
        <div class="menu">
          <a href="index.php">
            <img class="navbar-logo" src="./images/logo.png" alt="Logo" />
          </a>
          <input type="checkbox" id="menu-toggle" />
          <label for="menu-toggle" class="menu-icon">&#9776;</label>
          <ul class="items" id="navigation">
            <li><a href="index.php">Home</a></li>
            <li><a href="jobs.php">Job Descriptions</a></li>
            <li><a href="apply.php">Apply</a></li>
            <li><a href="about.php" class="active">About Us</a></li>
            <li><a href="enhancements.php">Enhancements</a></li>
            <li><a href="manage.php">Manage</a></li>
          </ul>
        </div>
      </nav>
    </header>
